spring:
  datasource:
    url: jdbc:mysql://localhost:3307/study?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true